#!/usr/bin/env bash 
alias ,gp="git commit -am saving; git push; git status"

,jl() {
   f=$1; shift
   julia -O0 --compile=min --startup=no $1.jl $*
}

,md() { 
  gawk ' 
  PASS==1 && /^##/ {k=$2 ; next}
  PASS==1 {TXT["<"FILENAME" "k">"] = TXT["<"FILENAME" "k">"] sep $0 ; sep="\n"}
  PASS==2 {print}
  PASS==2 && /^```julia/ {   
    print(TXT[$2" "$3],"\n```")
    USED[$2" "$3]++
    skip()
    next
  }
  END { Head="\nWARNINGS:\n"
        for(k in TXT)
          if (USED[k] != 1) {
             print(Head"\t "(USED[k]+0)" "k)>"/dev/stderr" 
             Head=""}}
 
 function skip() { while(getline >0) if (/^```/) return; }
 ' PASS=1 *.jl PASS=2 $1 > _tmp
 mv _tmp $1
}
